name: "Actions Status Notifier"
description: "Post Github Actions CI status to Discord"
author: "taiki-nd"

inputs:
  webhook:
    description: "Discord webhook endpoint."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    WEBHOOK_URL: ${{ inputs.webhook }}
    GITHUB_ACTIONS_STATUS: ${{ job.status }}
    GITHUB_ACTIONS_COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
    GITHUB_ACTIONS_PR_TITLE: ${{ github.event.pull_request.title }}
    GITHUB_ACTIONS_PR_URL: ${{ github.event.pull_request.html_url }}
