name: "Actions Status Notifier"
description: "Post Github Actions CI status to Discord"
author: "taiki-nd"

inputs:
  webhook:
    description: "Discord webhook endpoint."
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print current directory
      run: pwd

    - name: List directory contents
      run: ls -la

    - name: List directory contents of cmd
      run: ls -la cmd/

    - name: Show go.mod file
      run: cat go.mod

    - name: Run action
      run: go run ${{ github.action_path }}/cmd/main.go
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook }}
        GITHUB_ACTIONS_STATUS: ${{ job.status }}
        GITHUB_ACTIONS_COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
        GITHUB_ACTIONS_PR_TITLE: ${{ github.event.pull_request.title }}
        GITHUB_ACTIONS_PR_URL: ${{ github.event.pull_request.html_url }}
