name: "Actions Status Discord"
description: "Post Github Actions CI status to Discord"
author: "taiki-nd"

inputs:
  webhook:
    description: "Discord webhook endpoint."
    required: true
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}
  commit_message:
    description: "Commit message. Should be bound to github.event.commits[0].message."
    required: false
    default: ${{ github.event.commits[0].message }}

runs:
  using: "composite"
  steps:
    - run: go run cmd/main.go
      env:
        WEBHOOK_URL: ${{ inputs.webhook }}
        GITHUB_ACTIONS_STATUS: ${{ inputs.status }}
        GITHUB_ACTIONS_COMMIT_MESSAGE: ${{ inputs.commit_message }}
