name: "Actions Status Notifier"
description: "Post Github Actions CI status to Discord"
author: "taiki-nd"

inputs:
  webhook:
    description: "Discord webhook endpoint."
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Echo environment
      run: |
        echo "${{ inputs.webhook }}"
        echo "${{ job.status }}"
        echo "${{ github.event.commits[0].message }}"
        echo "${{ github.event.pull_request.title }}"
        echo "${{ github.event.pull_request.html_url }}"
        echo "${{ github.action_path }}"
      shell: bash

    - name: pwd
      run: pwd
      shell: bash

    - name: ls
      run: ls -la
      shell: bash

    - name: Download go mod
      run: go mod download
      shell: bash

    - name: Run action
      run: go run ${{ github.action_path }}/main.go
      shell: bash
