name: "Actions Status Notifier"
description: "Post Github Actions CI status to Discord"
author: "taiki-nd"

inputs:
  webhook:
    description: "Discord webhook endpoint."
    required: true

runs:
  using: "composite"
  steps:
    - run: go run cmd/main.go
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook }}
        GITHUB_ACTIONS_STATUS: ${{ job.status }}
        GITHUB_ACTIONS_COMMIT_MESSAGE: ${{ inputs.commit_message }}
        GITHUB_ACTIONS_PR_TITLE: ${{ github.event.pull_request.title }}
        GITHUB_ACTIONS_PR_URL: ${{ github.event.pull_request.html_url }}
