name: "Do Actions Status Notifier"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  do-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environment
          run: |
            echo "WEBHOOK_URL=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
            echo "GITHUB_STATUS=${{ job.status }}" >> $GITHUB_ENV
            echo "GITHUB_COMMIT_MESSAGE=${{ github.event.commits[0].message }}" >> $GITHUB_ENV
            echo "GITHUB_PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
            echo "GITHUB_PR_URL=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV

      - name: Run action
        if: Always()
        uses: taiki-nd/actions_notification@v0.0.14
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
