name: "Do Actions Status Notifier"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  do-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run action
        if: Always()
        uses: taiki-nd/actions_notification@v0.0.15
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
