name: Actions Notification Test
on: [pull_request, push]

jobs:
  actions-notification-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: echo "INPUT_WEBHOOK=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run action
        if: Always()
        run: go run cmd/main.go
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_ACTIONS_STATUS: ${{ job.status }}
          GITHUB_ACTIONS_EVENT: ${{ github.event.commits[0].message }}

      - name: Run action
        if: Always()
        run: go run cmd/main.go
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_ACTIONS_STATUS: "failure"
          GITHUB_ACTIONS_EVENT: ${{ github.event.commits[0].message }}

      - name: Run action
        if: Always()
        run: go run cmd/main.go
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_ACTIONS_STATUS: "cancelled"
          GITHUB_ACTIONS_COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
