name: Actions Notification Test
on: [pull_request, push]

jobs:
  actions-notification-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: echo "INPUT_WEBHOOK=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV

      - name: Run action
        run: go run cmd/main.go cicd
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - name: force failure
        run: exit 1

      - name: Run action
        if: Always()
        run: go run cmd/main.go cicd
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          GITHUB_ACTIONS_STATUS: ${{ job.status }}
