name: Actions Notification Test
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: echo "INPUT_WEBHOOK=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
      - name: docker build
        run: docker build -t notification .
      - name: docker run
        run: docker run -e INPUT_WEBHOOK=$INPUT_WEBHOOK notification
