name: Actions Notification Test
on: [pull_request, push]

jobs:
  actions-notification-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print environment variables
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "SHA: $GITHUB_SHA"
          echo "Ref: $GITHUB_REF"
          echo "Actor: $GITHUB_ACTOR"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Event Name: $GITHUB_EVENT_NAME"
          echo "Workspace: $GITHUB_WORKSPACE"
          echo "Run ID: $GITHUB_RUN_ID"
          echo "Server URL: $GITHUB_SERVER_URL"
      - name: Setup environment
        run: echo "INPUT_WEBHOOK=${{ secrets.WEBHOOK_URL }}" >> $GITHUB_ENV
      - name: Run action
        run: go run cmd/main.go
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
